### ISSUE TITLE
Is the WJC include a way to login to the server?

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-javascript-client#20]
For now I don't see any login / logout methods.

Is it plan to add them in the Wakanda Javascript Client?

**Comment by hamzahik** [comment]
@Ganbin the wiki does not mention it but in the tests you can find some examples 

https://github.com/Wakanda/wakanda-javascript-client/blob/master/test/spec/05-directory.spec.js

We will add a section about the directory to the wiki asap.

Thank you for reporting this.
