### ISSUE TITLE
Can't get the catalog

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-javascript-client#21]
Hello,

I'm trying to use the wakanda-javascript-client 0.3.2, but I can't get it work. 

````
let wakanda = new WakandaClient();
wakanda.getCatalog().then(function (ds) {
	debugger;
	ds.Employee.query({
		filter: 'firstName == :1',
		params: ['*']
	}).then(function (evt) {
		debugger;
	});
});
````

I get this error : `catalog-business.ts:138 : Uncaught (in promise) Error: Needed  dataClass is not present on catalog(…)`

It is really hard to debug because it use transpilled code from typeScript :'(.

It look like there is a empty string in the dataclass list.

I have created my dataclasses with the Model API this way : 

````
model.Company = new DataClass('Companies');
model.Company.ID = new Attribute('storage', 'long', 'key auto');
model.Company.name = new Attribute('storage', 'string', 'b-tree');
model.Company.allEmployees = new Attribute('relatedEntities', 'Employees', 'company',{reversePath:true});
 
//Creating the Person class
model.Person = new DataClass("People");
model.Person.ID = new Attribute("storage", "long", "key auto"); 
model.Person.firstName = new Attribute("storage", "string", "btree"); 
model.Person.lastName = new Attribute("storage", "string", "btree"); 
model.Person.fullName = new Attribute("calculated", "string"); 
 
//Creating the derived Employee class
model.Employee = new DataClass ("Employees", "public", "Person");
model.Employee.hireDate = new Attribute("storage", "date"); // adding specific attributes to the derived class
model.Employee.accessLevel = new Attribute("storage", "long");
model.Employee.salary = new Attribute("storage", "number");
model.Employee.company = new Attribute('relatedEntity', 'Company', 'Company');
 
//onGet for the calculated atttibute
model.Person.fullName.onGet = function()
{
    return this.firstName + ' ' + this.lastName;
}
//onSet for the fullName attribute
model.Person.fullName.onSet = function()
{
    var names = value.split(' '); //split value into an array  
    this.firstName = names[0];   
    this.lastName = names[1]; 
}
````

So I can't go forward to my test with aurelia because I can't access my data.

Please need some help.

Thanks

**Comment by Ganbin** [comment]
I see that in another project, the catalog is well get. So maybe it is related to the fact that I have add my classes with the model API?

**Comment by hamzahik** [comment]
Hello @Ganbin,

what response do you receive when you open /rest/$catalog on the brower ?

**Comment by Ganbin** [comment]
I get that : ````
{"dataClasses":[{"name":"Company","uri":"/rest/$catalog/Company","dataURI":"/rest/Company"},{"name":"Employee","uri":"/rest/$catalog/Employee","dataURI":"/rest/Employee"},{"name":"Person","uri":"/rest/$catalog/Person","dataURI":"/rest/Person"}]}
````

**Comment by fredGandelot** [comment]
@Ganbin it appears then that the catalog is indeed well defined.
It simple SSJS request might confirm it. 
`ds.Company.all()` for instance.

can you confirm that you get the collection back ?

**Comment by Ganbin** [comment]
Yes the server side code return all my entities.

**Comment by hamzahik** [comment]
@Ganbin and on the browser `/rest/Employee` returns the list of employees ?

**Comment by mrblackus** [comment]
Hi @Ganbin, you're right, this error is raised by WakandaClient because it's looking for a dataClass for a relational attribute (entity or entity collection attribute) that has not been retrieved.

Strange thing is, the apparently missing dataClass has an empty string as name.

Can you give me what you get from `/rest/$catalog/$all` call? There probably is a type on this JSON which is missing or have an invalid format.

**Comment by Ganbin** [comment]
`/rest/Employee`return me the list of the employees.

`/rest/$catalog/$all` give me 

`````
{"dataClasses":[{"name":"Company","className":"Company","collectionName":"Companies","scope":"public","dataURI":"/rest/Company","noEdit":true,"noSave":true,"attributes":[{"name":"ID","kind":"storage","scope":"public","indexed":true,"type":"long","identifying":true},{"name":"name","kind":"storage","scope":"public","type":"string"},{"name":"allEmployees","kind":"relatedEntities","scope":"public","type":"Employees","reversePath":true,"path":"company"}],"key":[{"name":"ID"}]},{"name":"Employee","className":"Employee","collectionName":"Employees","scope":"public","dataURI":"/rest/Employee","noEdit":true,"noSave":true,"attributes":[{"name":"ID","kind":"storage","scope":"public","indexed":true,"type":"long","identifying":true},{"name":"firstName","kind":"storage","scope":"public","indexed":true,"type":"string"},{"name":"lastName","kind":"storage","scope":"public","indexed":true,"type":"string"},{"name":"fullName","kind":"calculated","scope":"public","type":"string"},{"name":"hireDate","kind":"storage","scope":"public","type":"date","simpleDate":true},{"name":"accessLevel","kind":"storage","scope":"public","type":"long"},{"name":"salary","kind":"storage","scope":"public","type":"number"},{"name":"company","kind":"relatedEntity","scope":"public","type":"Company","path":"Company"}],"key":[{"name":"ID"}]},{"name":"Person","className":"Person","collectionName":"People","scope":"public","dataURI":"/rest/Person","noEdit":true,"noSave":true,"attributes":[{"name":"ID","kind":"storage","scope":"public","indexed":true,"type":"long","identifying":true},{"name":"firstName","kind":"storage","scope":"public","indexed":true,"type":"string"},{"name":"lastName","kind":"storage","scope":"public","indexed":true,"type":"string"},{"name":"fullName","kind":"calculated","scope":"public","type":"string"}],"key":[{"name":"ID"}]}]}
`````

**Comment by mrblackus** [comment]
Hi,

I got what happens. WakandaClient expects dataClass `collectionName` attribute to be the name of the dataClass with `collection` appended. For example, for a `Company` dataClass, its `collectionName` would be `CompanyCollection`.

When manually defining your model, you pass other name as an argument to the `new DataClass()` constructor, resulting on a different `collectionName` format.

For now, I suggest you to change the names you give to `new DataClass()` constructors to follow this convention, awaiting for a fix on WakandaClient.

NB: result will be the same on Angular-Wakanda 1.0.0+ because it relies on WakandaClient.

**Comment by Ganbin** [comment]
Great. Joy. Thanks, I have change the default collection name with the "_dataclassName_ + _Collection_" and now I can have access to all my dataclass.

Thanks for the good support.

**Comment by mrblackus** [comment]
Glad it helps! I recorded the bug internally, if we deliver a fix for this issue, I'll let you know here.
