### ISSUE TITLE
Get an date attribute give strange result

### ISSUE THREAD

**Issue by Ganbin** [Wakanda/wakanda-javascript-client#22]
As we can see in my pictures, the date attribute is get in this format `13!11!1990` on the client side. But on the server, we can see the attribue well saved in the right format.

![datewak-clientget](https://cloud.githubusercontent.com/assets/1487962/15826173/d1e91434-2c06-11e6-85a4-2dd758b3f54f.png)
![datessjs](https://cloud.githubusercontent.com/assets/1487962/15826176/d6f754e0-2c06-11e6-8073-0aaa37c604e9.png)

I'm using the same project with aurelia than the bug for the catalog.

I'm using a `input type="date"` to enter a date, on the server it is well saved, but when I get back my entity, I get it with this strange format. Is it a bug or a problem with my model?

**Comment by mrblackus** [comment]
HI @Ganbin, indeed there is something wrong with that. I'm checking this and come to you soon.

Thanks for the report.

**Comment by mrblackus** [comment]
It's quite strange, I can't reproduce it.

Can you give me the WakandaClient version you are using, and what you get from the REST API when performing your request (*Network* tab on the inspector, subtab *Preview*)  ?

**Comment by Ganbin** [comment]
Here is what I get from the server : 
![daterest](https://cloud.githubusercontent.com/assets/1487962/15855249/c18f285a-2cae-11e6-946c-6d584dd918dd.png)

So it look like it is what the server send to me.

**Comment by Ganbin** [comment]
Ok I see now where is the problem. I have this line in my model definition : `model.Employee.hireDate = new Attribute("storage", "date");`

So the model see that like a `dateOnly` attribute. So I have add an option, that I have found in the doc. Now it look like that : `model.Employee.hireDate = new Attribute("storage", "date",{simpleDate:false});`

And now I get the right format date : 
![daterestok2](https://cloud.githubusercontent.com/assets/1487962/15855638/e3219ee2-2cb0-11e6-8afe-b54516df9e9c.png)

Sorry for the disturbance.

**Comment by mrblackus** [comment]
No problem!
