### ISSUE TITLE
Version 0.5.0 has issue with wakanda server port number of 8081

### ISSUE THREAD

**Issue by yongks** [Wakanda/wakanda-javascript-client#46]
After upgrade to version 0.5.0, the :8081 port setting below is ignored. I found out from chrome console that it always point to current port number when executing wakanda command, rather then 8081 as below.

`this._client = new WakandaClient("http://127.0.0.1:8081");
`

After fallback to 0.4.0, things works just like before. I am using angular2.1.0.

**Comment by hamzahik** [comment]
@ibtissamO @yboukhata can you please look into this asap

**Comment by yboukhata** [comment]
Hi @yongks,

We have not update the documentation yet, because it's a pre-release version.

You can fix you issue just  just passing an object to the constructor like this :

```
this._client = new WakandaClient({ host: "http://127.0.0.1:8081" }); 
```
