### ISSUE TITLE
error in wakanda-client constructor

### ISSUE THREAD

**Issue by adithya003** [Wakanda/wakanda-javascript-client#57]
TypeError: no_promise_1.WakandaClient is not a constructor

I tried creating a client inside my TS file and when compiling i am getting the above error

Here is my TS
import {Component} from '@angular/core';

import {WakandaClient} from 'wakanda-client/browser/no-promise';
import {ROUTER_DIRECTIVES, CanActivate,Router} from '@angular/router';

import {GridOptions} from 'ag-grid/main';
import {SquareComponent} from "./square.component";
import {ParamsComponent} from "./params.component";
import {CubeComponent} from "./cube.component";
import {CurrencyComponent} from "./currency.component";

@Component({
    moduleId: module.id,
    selector: 'ag-from-component',
    templateUrl: 'from-component.component.html'
})
export class FromComponentComponent {
    public gridOptions:GridOptions;
	let client = new WakandaClient();
    constructor() {
        this.gridOptions = <GridOptions>{};
        this.gridOptions.rowData = this.createRowData();
        this.gridOptions.columnDefs = this.createColumnDefs();
    }
}

**Comment by yousfiSaad** [comment]
Try this : 
let client = new WakandaClient({}); //with an object as a parameter
