### ISSUE TITLE
There is no way to dynamically request catalog based on permissions

### ISSUE THREAD

**Issue by dstone760** [Wakanda/wakanda-javascript-client#60]
Right now, we're in an angular-2/typescript environment thats interacting with our Wakanda server via the javascript client. Our problem is that we need a way to say "when getting the catalog, only get datastores that the current user has access to". 

So, while we do obviously have access to our permissions file, we would have to hard code an additional system of looking up those datastores- one that wouldn't be directly in sync if we ever change permissions. 

There should be a system built in, so when you do client.getCatalog() it ONLY returns the datastores a user has permission to get. This problem is especially crippling to us because of typescript, we only want to construct the catalog once since it's on an object we're tossing around. If, however, we had a way to say, for example
`let permissions:Array<String> = client.directory.getAccessibleDatastores();
client.getCatalog(permissions).then(......
`
we would be set. But as I can tell from the only documentation I can find (https://github.com/Wakanda/wakanda-javascript-client/wiki/Quickstart) that isn't possible.

**Comment by dstone760** [comment]
I wouldn't necessarily call this issue solved, but we found that the problem came from the "describe" permission. Since this client is easily capable of loading the entire catalog, the dataclasses which have the describe permission were breaking it. It would seem that if you want to load the entire catalog, then there should be an easy way to choose to not load the dataclasses which you do not have permission to describe. But, after some internal discussion, we have settled on changing the nature of our describe permission. Everyone logged in can describe a dataclass, but not otherwise. This is secure enough for us now, but in the future, we feel like there should be a way to not load dataclasses which you do not have permission to load.

**Comment by fredGandelot** [comment]
Hello @dstone760  ,

Indeed when setting a Describe permission attached to a  single Dataclass1, the whole /rest/$catalog/ will return an error . (even if all the other dataclasses have no describe permissions) 

We can discuss a feature to modify this behaviour  (the rest/$catalog would only reply the dataclasses the user has access to.) That would definitely ease the process.

However in the mean time  you can manually the dataclasses in the getCatalog method (getCatalog("datacl1 , dataC2" )

**Comment by fredGandelot** [comment]
Hi @dstone760  ,

FYI, your request has been heard. 
Now when using by default the getCatalog() method (https://github.com/Wakanda/wakanda-javascript-client/wiki/Quickstart#getting-a-catalog)  you'll get only the Dataclasses the user has access (based on the Describe Permission)

It's been developed already, and (ll be integrated in the next version .
Fred

**Comment by dstone760** [comment]
Thank you! Glad to hear back.
