### ISSUE TITLE
Client sends request to wrong port number (how to configure?)

### ISSUE THREAD

**Issue by Fuchssystems** [Wakanda/wakanda-javascript-client#67]
Using webpack development server with react
Create with success a wakanda client instance (singleton):

 this.wakClient = new WakandaClient('http://localhost:8081');

Then, when trying to login with 
wakClient.directory.login('test2', 'test2')
i see in Chrome that wkanda.client.min.js postet

http://localhost:3000/rest/$directory/login

usingt the wrong port number.

Question: how to configure?
Or bug?

**Comment by hamzahik** [comment]
@Fuchssystems as you can see in the example file `instantiate-domain.js` at https://wakanda.github.io/doc/#/guide?section=main-data-cs-instance

You need to pass in the domain as follows:

```javascript
this.wakClient = new WakandaClient.WakandaClient({ host : "http://localhost:8081"});
```
