### ISSUE TITLE
Session-ID cookie 'WASID" hat HTTP-Only flag set so it can not be read on Chrome, IE

### ISSUE THREAD

**Issue by Fuchssystems** [Wakanda/wakanda-javascript-client#74]
The cookie "WASID" set by wakanda-client can not be read on Chrome.
(document.cookie always returns empty string)
Reason: Flag HTTP-Only flag is set for the cookie.

See
https://stackoverflow.com/questions/8064318/how-to-read-a-secure-cookie-using-javascript
"Different Browsers enable different security measures when the HTTPOnly flag is set. For instance Opera and Safari do not prevent javascript from writing to the cookie. However, reading is always forbidden on the latest version of all major browsers."

How then do I get the Session-ID on the client?

wakanda-client documentation: lacks setting of cookie.

**Comment by hamzahik** [comment]
It is very dangerous to let JavaScript access the session ID cookie.  You can read more about the subject at https://en.wikipedia.org/wiki/Cross-site_scripting#Cookie_security

I don't see why you would need to access the session ID on the client side. Can you give more details about your use case ?

**Comment by Fuchssystems** [comment]
Yes, setting the HTTPOnly flag makes sense.
Issue closed.

Reason: the session cookie WASID is not send to the server when I call datastore methods via REST.
However, calling methods with wakanda-client transmitts the cookie to the server.
For this I was trying to send the cookie myself attached as an object to restore the session on the server myself.
See that wakanda-clients Request-method is "POST" and mine is "OPTIONS" and will look into this.

**Comment by Fuchssystems** [comment]
Reason for that the cookie was not transmitted was that my "fetch" (javascript) did not have the attribute "credentials: include" set.
