### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-javascript-client#9]
I'm delighted you have produced WakandaClient.

However, there is no documentation.

You have good instructions on how to install it, but how do I actually use it in an application?

What commands are available etc?

I'm really looking forward to more details about this product as they become available.

FWIW I am developing in Angular2

**Comment by mrblackus** [comment]
Hi Chris,
There is no complete documentation at this time (it will come soon), but there is a [Quickstart Page](https://github.com/Wakanda/wakanda-javascript-client/wiki/Quickstart), on the repo wiki, that explains the basics of Wakanda-Client.

Feel free to reach us if you have further questions.

**Comment by jeffgrann** [comment]
Please be sure to announce when the documentation is available in the Wakanda Weekly newsletter.

**Comment by chriscurnow** [comment]
Hi Mathieu,

That’s great. I’m happy with the QuickStart to get me going.

I didn’t see it when I looked at the page yesterday.

Just a suggestion but perhaps you could include a link to the QuickStart in the ReadMe.

Regardless, it’s great the work you guys have done on this.

Best regards
Chris

On 4 Apr 2016, at 5:42 PM, Mathieu Savy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Chris,
There is no complete documentation at this time (it will come soon), but there is a Quickstart Page<https://github.com/Wakanda/wakanda-javascript-client/wiki/Quickstart>, on the repo wiki, that explains the basics of Wakanda-Client.

Feel free to reach us if you have further questions.

**Comment by chriscurnow** [comment]
@mrblackus 

> There is no complete documentation at this time (it will come soon)

Any news on the documentation? It's now getting towards the end of September and we thought it was coming soon in April;)

**Comment by hamzahik** [comment]
I'm closing this since the documentation is available for a while now at https://wakanda.github.io/doc/#/guide?section=main-data-cs
